
"""Práctico 1: Estructuras secuenciales

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uDK4kpM2ksrU5U8mZq7ZXnEESQAqpqxW

1) Crear un programa que imprima por pantalla el mensaje: “Hola Mundo!”.
"""

print("Hola Mundo!")

"""2) Crear un programa que pida al usuario su nombre e imprima por pantalla un saludo usando
el nombre ingresado. Por ejemplo: si el usuario ingresa “Marcos”, el programa debe imprimir
por pantalla “Hola Marcos!”. Consejo: esto será más sencillo si utilizas print(f…) para
realizar la impresión por pantalla.
"""

nombre = input("Ingrese su nombre: ")
print(f"Hola {nombre}!")

"""3) Crear un programa que pida al usuario su nombre, apellido, edad y lugar de residencia e
imprima por pantalla una oración con los datos ingresados. Por ejemplo: si el usuario ingresa
“Marcos”, “Pérez”, “30” y “Argentina”, el programa debe imprimir “Soy Marcos Pérez, tengo 30
años y vivo en Argentina”. Consejo: esto será más sencillo si utilizas print(f…) para realizar
la impresión por pantalla.
"""

nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
edad = input("Ingrese su edad: ")
lugar = input("Ingrese su lugar de residencia: ")
print(f"Soy {nombre} {apellido}, tengo {edad} años y vivo en {lugar}.")

"""4) Crear un programa que pida al usuario el radio de un círculo e imprima por pantalla su área y
su perímetro..
"""

radio = float(input("Ingrese el radio del círculo: "))
area = 3.14 * radio ** 2
perimetro = 2 * 3.14 * radio
print(f"El área del círculo es {area} y el perímetro es {perimetro}.")

"""5) Crear un programa que pida al usuario una cantidad de segundos e imprima por pantalla a
cuántas horas equivale.
"""

segundos = int(input("Ingrese la cantidad de segundos: "))
horas = segundos / 3600
print(f"{segundos} segundos equivalen a {horas} horas.")

"""6) Crear un programa que pida al usuario un número e imprima por pantalla la tabla de
multiplicar de dicho número.
"""

numero= int(input("Ingrese un numero: "))
for i in range(1,11):
    print(f"{numero} x {i} = {numero * i}")

"""7) Crear un programa que pida al usuario dos números enteros distintos del 0 y muestre por
pantalla el resultado de sumarlos, dividirlos, multiplicarlos y restarlos.
"""

num1= int(input("Ingrese el primer numero: "))
num2= int(input("Ingrese el segundo numero: "))
suma= num1 + num2
division= num1 / num2
multiplicacion= num1 * num2
resta= num1 - num2
print("La suma es: ", suma)
print("La division es: ", division)
print("La multiplicacion es: ", multiplicacion)
print("La resta es: ", resta)

"""8) Crear un programa que pida al usuario su altura y su peso e imprima por pantalla su índice
de masa corporal. Tener en cuenta que el índice de masa corporal se calcula del siguiente
modo:  

"""

altura = int(input("Ingrese su altura en centímetros: "))
peso_kg = float(input("Ingrese su peso en kilogramos: "))
altura_m = altura / 100  # altura a metros
imc = peso_kg / altura_m ** 2
print("Su índice de masa corporal es:", round(imc, 2))

""" 9) Crear un programa que pida al usuario una temperatura en grados Celsius e imprima por
pantalla su equivalente en grados Fahrenheit. Tener en cuenta la siguiente equivalencia:
�
�𝑒𝑚𝑝𝑒𝑟𝑎𝑡𝑢𝑟𝑎 𝑒𝑛 𝐹𝑎ℎ𝑟𝑒𝑛ℎ𝑒𝑖𝑡 = 9
 5
 . 𝑇𝑒𝑚𝑝𝑒𝑟𝑎𝑡𝑢𝑟𝑎 𝑒𝑛 𝐶𝑒𝑙𝑠𝑖𝑢𝑠   + 32
"""

gradcel= int(input("Ingrese la temperatura en grados Celsius: "))
gradfah= 9/5 * gradcel + 32
print("La temperatura en grados Fahrenheit es: ", gradfah)

""" 10) Crear un programa que pida al usuario  3 números e imprima por pantalla el promedio de
dichos números.
"""

num1= int(input("Ingrese el primer numero: "))
num2= int(input("Ingrese el segundo numero: "))
num3= int(input("Ingrese el tercer numero: "))
print("El promedio de los numeros es: ", (num1 + num2 + num3) / 3)