# -*- coding: utf-8 -*-
"""Práctico 11: Aplicación de la Recursividad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FfPByvp7Ie62hqXH9CnUCfRjLdrWRq_u

#Práctico 11: Aplicación de la Recursividad

### Juan Facundo Escalante DNI:24927651

1) Crea una función recursiva que calcule el factorial de un número. Luego, utiliza esa
función para calcular y mostrar en pantalla el factorial de todos los números enteros
entre 1 y el número que indique el usuario.
"""

def factorial_recur(numero):                  # Defino una función recursiva para calcular el factorial de un número
    if numero == 0:                           # Si el número es 0, devuelvo 1 porque ese es el caso base del factorial
        return 1                              # Retorno 1 como resultado del caso base
    else:                                     # Si el número no es 0, sigo con la recursión
        return numero * factorial_recur(numero - 1)  # Multiplico el número actual por el factorial del anterior

pedir_numero = int(input("Ingrese un número positivo: "))  # Le pido al usuario que ingrese un número entero positivo

for i in range(1, pedir_numero + 1):                       # Recorro desde 1 hasta el número que ingresó el usuario, inclusive
    print(f"El factorial de {i} es {factorial_recur(i)}")  # Muestro en pantalla el factorial de cada número usando la función recursiva

"""2) Crea una función recursiva que calcule el valor de la serie de Fibonacci en la posición
indicada. Posteriormente, muestra la serie completa hasta la posición que el usuario
especifique.
"""

def fibonacci(n):                             # Defino una función recursiva para calcular el valor de la serie de Fibonacci en la posición n
    if n == 0:                                # Si n es 0, devuelvo 0 porque es el primer número de la serie
        return 0
    elif n == 1:                              # Si n es 1, devuelvo 1 porque es el segundo número de la serie
        return 1
    else:                                     # Si n es mayor que 1, sumo los dos valores anteriores de la serie
        return fibonacci(n - 1) + fibonacci(n - 2)

# Bucle interactivo para pedir posiciones al usuario
while True:                                  # Inicio un bucle infinito para que el usuario pueda ingresar varias posiciones
    entrada = input("Ingrese un numero (o 'q' para terminar): ")  # Le pido al usuario una posición o que escriba 'q' para salir

    if entrada.lower() == "q":                                 # Si el usuario escribe 'q', cierro el programa
        print("¡Hasta luego!")                                    # Le doy un mensaje de despedida
        break                                                 # Salgo del bucle

    if not entrada.isdigit():                                 # Verifico que la entrada sea un número válido
        print("Por favor, ingrese un número válido.")           # Si no lo es, muestro un mensaje de error
        continue                                               # Vuelvo al inicio del bucle para pedir otra entrada

    pedir_numero = int(entrada)                                  # Convierto la entrada en un número entero
    print("Serie de Fibonacci:")                                # Muestro un encabezado para la serie

    i = 0                                  # Inicializo el contador en 0
    while i <= pedir_numero:                              # Recorro desde 0 hasta la posición ingresada
        print(f"F({i}) = {fibonacci(i)}")                 # Muestro el valor de Fibonacci en la posición i
        i += 1                                           # Incremento el contador para pasar a la siguiente posición

"""3) Crea una función recursiva que calcule la potencia de un número base elevado a un
exponente, utilizando la fórmula 𝑛𝑚 = 𝑛 ∗ 𝑛(𝑚−1). Prueba esta función en un
algoritmo general.
"""

def potencia_recursiva(base, exponente):                          # Defino una función recursiva que calcula la potencia de un número
    if exponente == 0:                                            # Si el exponente es 0, devuelvo 1 porque cualquier número elevado a 0 es 1
        return 1
    else:                                                         # Si el exponente es mayor que 0, multiplico la base por la potencia de la base con exponente - 1
        return base * potencia_recursiva(base, exponente - 1)

while True:                                                    # Inicio un bucle infinito para que el usuario pueda calcular varias potencias
  entrada_base = input("Ingrese la base ( o q para salir): ")  # Le pido al usuario que ingrese la base o que escriba 'q' para salir
  if entrada_base.lower() == "q":                                # Si el usuario escribe 'q', cierro el programa
    print("¡Hasta luego!")                                      # Muestro un mensaje de despedida
    break                                                      # Salgo del bucle

  entra_exponente = input("Ingrese el exponente: ")                # Le pido al usuario que ingrese el exponente

  if not entrada_base.isdigit() or not entra_exponente.isdigit():  # Verifico que ambas entradas sean números válidos
    print("Por favor, ingrese números válidos.")                   # Si no lo son, muestro un mensaje de error
    continue                                                      # Vuelvo al inicio del bucle para pedir otra entrada

  base = int(entrada_base)                                       # Convierto la base a número entero
  exponente = int(entra_exponente)                               # Convierto el exponente a número entero

  resultado = potencia_recursiva(base, exponente)                 # Llamo a la función recursiva para calcular la potencia
  print(f"{base} elevado a {exponente} es {resultado}\n")          # Muestro el resultado con un salto de línea al final

"""4) Crear una función recursiva en Python que reciba un número entero positivo en base
decimal y devuelva su representación en binario como una cadena de texto.
"""

def decimal_binario(n):                                                  # Defino una función recursiva que convierte un número decimal a binario
  if n == 0:                                                           # Si el número es 0, devuelvo "0" como caso base
    return "0"
  elif n == 1:                                                          # Si el número es 1, devuelvo "1" como otro caso base
    return "1"
  else:                                                                # Si el número es mayor que 1, sigo dividiendo por 2 y concateno el residuo
    return decimal_binario(n // 2) + str(n % 2)                         # Llamo recursivamente con n//2 y agrego el bit actual

while True:                                                               # Inicio un bucle infinito para que el usuario pueda convertir varios números
    entrada = input("Ingrese un número entero positivo (o 'q' para salir): ")  # Le pido al usuario un número o que escriba 'q' para salir

    if entrada.lower() == "q":                                           # Si el usuario escribe 'q', cierro el programa
        print("¡Hasta luego!")                                        # Muestro un mensaje de despedida
        break                                                         # Salgo del bucle

    if not entrada.isdigit():                                  # Verifico que la entrada sea un número válido
        print("Por favor, ingrese un número válido.")           # Si no lo es, muestro un mensaje de error
        continue                                               # Vuelvo al inicio del bucle para pedir otra entrada

    numero = int(entrada)                                     # Convierto la entrada en un número entero
    binario = decimal_binario(numero)                            # Llamo a la función recursiva para obtener el binario
    print(f"El número {numero} en binario es {binario}\n")  # Muestro el resultado con un salto de línea

"""5) Implementá una función recursiva llamada es_palindromo(palabra) que reciba una
cadena de texto sin espacios ni tildes, y devuelva True si es un palíndromo o False si no
lo es.

      Requisitos:
      
      La solución debe ser recursiva.
      
      No se debe usar [::-1] ni la función reversed().
"""

def es_palindromo(palabra):                                        # Defino una función recursiva que verifica si una palabra es un palíndromo
  if len(palabra) <= 1:                                             # Si la palabra tiene 0 o 1 letra, considero que es un palíndromo
    return True                                                   # Devuelvo True porque ya no hay más letras para comparar
  elif palabra[0] != palabra[-1]:                                 # Si la primera y la última letra son distintas, no es palíndromo
    return False                                                   # Devuelvo False porque no cumple la condición
  else:                                                           # Si las letras coinciden, sigo comparando el resto de la palabra
    return es_palindromo(palabra[1:-1])                           # Llamo a la función recursivamente sin los extremos

while True:                                                     # Inicio un bucle infinito para que el usuario pueda probar varias palabras
    entrada = input("Ingrese una palabra sin espacios ni tildes (o 'q' para salir): ")  # Le pido al usuario una palabra o que escriba 'q' para salir

    if entrada.lower() == "q":                                  # Si el usuario escribe 'q', cierro el programa
        print("¡Hasta luego!")                                  # Muestro un mensaje de despedida
        break                                                   # Salgo del bucle

    if not entrada.isalpha():                                    # Verifico que la entrada contenga solo letras
        print("Por favor, ingrese solo letras sin espacios ni símbolos.")  # Si no lo es, muestro un mensaje de error
        continue                                                # Vuelvo al inicio del bucle para pedir otra entrada

    resultado = es_palindromo(entrada.lower())                     # Llamo a la función con la palabra en minúsculas para evitar errores por mayúsculas
    if resultado:                                                   # Si la función devuelve True
        print(f"'{entrada}' es un palíndromo.\n")                     # Muestro que la palabra es un palíndromo
    else:                                                           # Si la función devuelve False
        print(f"'{entrada}' no es un palíndromo.\n")                   # Muestro que la palabra no es un palíndromo

"""6) Escribí una función recursiva en Python llamada suma_digitos(n) que reciba un
número entero positivo y devuelva la suma de todos sus dígitos.

     Restricciones:
         No se puede convertir el número a string.
         Usá operaciones matemáticas (%, //) y recursión.
"""

def suma_digitos(n):                                           # Defino una función recursiva que suma los dígitos de un número entero positivo
    if n < 10:                                                 # Si el número tiene un solo dígito, lo devuelvo directamente
        return n
    else:                                         # Si tiene más de un dígito, separo el último y sumo con el resto
        return (n % 10) + suma_digitos(n // 10)       # Uso % para obtener el último dígito y // para quitarlo

# Bucle interactivo para probar varios números
while True:                                                           # Inicio un bucle infinito para que el usuario pueda ingresar varios valores
    entrada = input("Ingrese un número entero positivo (o 'q' para salir): ")  # Le pido al usuario un número o que escriba 'q' para salir

    if entrada.lower() == "q":                                          # Si el usuario escribe 'q', cierro el programa
        print("¡Hasta luego!")                                         # Muestro un mensaje de despedida
        break                                                         # Salgo del bucle

    if not entrada.isdigit():                                        #  Verifico que la entrada sea un número válido
        print("Por favor, ingrese un número válido.")                    # Si no lo es, muestro un mensaje de error
        continue                                                        # Vuelvo al inicio del bucle para pedir otra entrada

    numero = int(entrada)                                                # Convierto la entrada en un número entero
    resultado = suma_digitos(numero)                               # Llamo a la función recursiva para calcular la suma de los dígitos
    print(f"La suma de los dígitos de {numero} es {resultado}\n")  # Muestro el resultado con un salto de línea

"""7) Un niño está construyendo una pirámide con bloques. En el nivel más bajo coloca n
bloques, en el siguiente nivel uno menos (n - 1), y así sucesivamente hasta llegar al
último nivel con un solo bloque.

      Escribí una función recursiva contar_bloques(n) que reciba el número de bloques en el nivel más bajo y devuelva el total de bloques que necesita para construir toda la pirámide.

      Ejemplos:

      contar_bloques(1)   → 1         (1)

      contar_bloques(2)   → 3         (2 + 1)

      contar_bloques(4)   → 10        (4 + 3 + 2 + 1)
"""

def contar_bloques(n):                                          # Defino la función recursiva que suma los bloques de cada nivel
    if n == 1:                                                  # Caso base: si el nivel tiene 1 bloque, devuelvo 1
        return 1
    else:                                                       # Paso recursivo: sumo los bloques del nivel actual con los del nivel superior
        return n + contar_bloques(n - 1)

# Bucle interactivo para ingresar varios valores
while True:
    entrada = input("Ingrese la cantidad de bloques en el nivel más bajo (o 'q' para salir): ")  # Le pido al usuario un número o que escriba 'q' para salir

    if entrada.lower() == "q":                                  # Si el usuario escribe 'q', cierro el programa
        print("¡Hasta luego!")                                  # Muestro un mensaje de despedida
        break                                                   # Salgo del bucle

    if not entrada.isdigit():                                   # Verifico que la entrada sea un número entero positivo
        print("Por favor, ingrese un número entero positivo.")  # Si no lo es, muestro un mensaje de error
        continue                                                # Vuelvo al inicio del bucle para pedir otra entrada

    n = int(entrada)                                            # Convierto la entrada en un número entero
    total = contar_bloques(n)                                  # Llamo a la función recursiva para calcular el total de bloques

    suma = " + ".join(str(i) for i in range(n, 0, -1))          # Construyo la suma como texto para mostrar cómo se calcula
    print(f"contar_bloques({n}) → {total}        ({suma})\n")  # Muestro el resultado con el formato del ejemplo

"""8) Escribí una función recursiva llamada contar_digito(numero, digito) que reciba un número entero positivo (numero) y un dígito (entre 0 y 9), y devuelva cuántas veces aparece ese dígito dentro del número.

      Ejemplos:
      
      contar_digito(12233421, 2)   → 3   
      contar_digito(5555, 5)       → 4  
"""

def contar_digito(numero, digito):  # Defino una función recursiva que cuenta cuántas veces aparece un dígito en un número
    if numero == 0:                         #Caso base: si el número ya llegó a 0, no quedan más dígitos por revisar
        return 0
    else:                                                            # Si todavía hay dígitos por revisar
        ultimo = numero % 10                                         # Obtengo el último dígito del número
        resto = numero // 10                                         # Elimino el último dígito para seguir con el resto
        if ultimo == digito:                                         # Si el último dígito coincide con el que estoy buscando
            return 1 + contar_digito(resto, digito)                  # Sumo 1 y sigo buscando en el resto
        else:                                                        # Si no coincide
            return contar_digito(resto, digito)                      # No sumo nada y sigo buscando en el resto

# Bucle interactivo para probar distintos valores
while True:
    entrada_numero = input("Ingrese un número entero positivo (o 'q' para salir): ")  # Le pido al usuario un número o que escriba 'q' para salir
    if entrada_numero.lower() == "q":                                            # Si el usuario escribe 'q', cierro el programa
        print("¡Hasta luego!")
        break

    entrada_digito = input("Ingrese el dígito que desea contar (0 a 9): ")  # Le pido el dígito que quiere contar

    if not entrada_numero.isdigit() or not entrada_digito.isdigit():  # Verifico que ambas entradas sean válidas
        print("Por favor, ingrese valores numéricos válidos.")
        continue

    numero = int(entrada_numero)                                     # Convierto el número a entero
    digito = int(entrada_digito)                                     # Convierto el dígito a entero

    if digito < 0 or digito > 9:                                     # Verifico que el dígito esté entre 0 y 9
        print("El dígito debe estar entre 0 y 9.")
        continue

    resultado = contar_digito(numero, digito)                                     # Llamo a la función recursiva
    print(f"El dígito {digito} aparece {resultado} veces en el número {numero}.\n")  # Muestro el resultado