# -*- coding: utf-8 -*-
"""Práctico 6: Estructuras de datos complejas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v8mRt5Jk3XrF_zR5LWYai4qO01AusZAZ

# Práctico 6: Estructuras de datos complejas

**Juan Facundo Escalante DNI:24927651**

1.Dado el diccionario precios_frutas

precios_frutas = {'Banana': 1200, 'Ananá': 2500, 'Melón': 3000, 'Uva':
1450}

Añadir las siguientes frutas con sus respectivos precios:

● Naranja = 1200
● Manzana = 1500
● Pera = 2300
"""

precios_frutas = {'Banana': 1200, 'Ananá': 2500, 'Melón': 3000, 'Uva': 1450}       # Creo un diccionario con algunas frutas y sus precios

precios_frutas['Naranja'] = 1200                                                  # Agrego la naranja al diccionario con su precio
precios_frutas['Manzana'] = 1500                                                  # Agrego la manzana con su precio correspondiente
precios_frutas['Pera'] = 2300                                                     # Finalmente, sumo la pera al listado

print(precios_frutas)                                                             # Muestro el diccionario completo con todas las frutas y precios

"""2) Siguiendo con el diccionario precios_frutas que resulta luego de ejecutar el código desarrollado en el punto anterior, actualizar los precios de las siguientes frutas:

● Banana = 1330
● Manzana = 1700
● Melón = 2800
"""

precios_frutas = {'Banana': 1200, 'Ananá': 2500, 'Melón': 3000, 'Uva': 1450, 'Naranja': 1200, 'Manzana': 1500, 'Pera': 2300}   # Inicializo el diccionario con frutas y sus precios

precios_frutas['Banana'] = 1330                                                                                              # Actualizo el precio de la banana porque subió un poco
precios_frutas['Manzana'] = 1700                                                                                             # Modifico el precio de la manzana, ahora cuesta más
precios_frutas['Melón'] = 2800                                                                                               # Ajusto el precio del melón, bajó un poco

print(precios_frutas)                                                                                                        # Muestro el diccionario actualizado con los nuevos precios

"""3) Siguiendo con el diccionario precios_frutas que resulta luego de ejecutar el código
desarrollado en el punto anterior, crear una lista que contenga únicamente las frutas sin los
precios.
"""

precios_frutas = {'Banana': 1330, 'Ananá': 2500, 'Melón': 2800, 'Uva': 1450, 'Naranja': 1200, 'Manzana': 1700, 'Pera': 2300}   # Tengo un diccionario con frutas y sus precios

lista_frutas = list(precios_frutas.keys())                                                                                  # Extraigo solo los nombres de las frutas y los convierto en una lista

print(lista_frutas)                                                                                                          # Muestro la lista de frutas por pantalla

"""4) Escribí un programa que permita almacenar y consultar números telefónicos.

• Permití al usuario cargar 5 contactos con su nombre como clave y número como valor.

• Luego, pedí un nombre y mostrale el número asociado, si existe.
"""

contactos = {}                                                                 # Creo un diccionario vacío para guardar los contactos

for i in range(5):                                                             # Repito el proceso 5 veces para cargar 5 contactos
    nombre = input("Ingrese el nombre del contacto: ")                         # Le pido al usuario el nombre del contacto
    numero = input("Ingrese el número de teléfono: ")                          # Le pido el número de teléfono
    contactos[nombre] = numero                                                 # Guardo el nombre como clave y el número como valor

consulta = input("Ingrese el nombre del contacto que desea consultar: ")      # Pido el nombre del contacto que quiere buscar

if consulta in contactos:                                                     # Verifico si el nombre está en el diccionario
    print("El número de teléfono de", consulta, "es", contactos[consulta])    # Si existe, muestro el número
else:                                                                          # Si no existe...
    print("No se encontró el contacto", consulta)                              # ...informo que no se encontró

"""5) Solicita al usuario una frase e imprime:

• Las palabras únicas (usando un set).

• Un diccionario con la cantidad de veces que aparece cada palabra.
"""

frase = input("Ingrese una frase: ")                                           # Le pido al usuario que escriba una frase

palabras = frase.split()                                                      # Divido la frase en palabras usando espacios como separador

palabras_unicas = set(palabras)                                               # Uso un set para quedarme solo con las palabras únicas

cantidad_palabras = {}                                                        # Creo un diccionario vacío para contar cuántas veces aparece cada palabra
for palabra in palabras:                                                      # Recorro cada palabra de la lista
    if palabra in cantidad_palabras:                                          # Si ya está en el diccionario...
        cantidad_palabras[palabra] += 1                                       # ...le sumo uno al contador
    else:                                                                     # Si no está...
        cantidad_palabras[palabra] = 1                                        # ...la agrego con valor 1

print("\nPalabras únicas: ")                                                  # Muestro el set de palabras únicas
print(palabras_unicas)

print("\nCantidad de veces que aparece cada palabra: ")                       # Muestro el diccionario con los conteos
print(cantidad_palabras)

"""6) Permití ingresar los nombres de 3 alumnos, y para cada uno una tupla de 3 notas.
Luego, mostrá el promedio de cada alumno.
"""

alumnos = {}                                  # Diccionario para guardar alumnos y sus notas

for i in range(3):                            # Repetimos el proceso para 3 alumnos
    while True:
        nombre = input(f"Ingrese el nombre del alumno {i+1}: ").strip()  # Pido el nombre
        if nombre.isalpha():                  # Verifico que solo tenga letras
            break
        print("⚠️ El nombre debe contener solo letras, sin espacios ni números.")  # Mensaje de error

    notas = []                                # Lista para guardar las 3 notas
    for j in range(3):
        while True:
            try:
                nota = float(input(f"Ingrese la nota {j+1} de {nombre} (0 a 10): "))  # Pido la nota
                if 0 <= nota <= 10:           # Verifico que esté entre 0 y 10
                    notas.append(nota)        # Guardo la nota
                    break
                else:
                    print("⚠️ La nota debe estar entre 0 y 10.")  # Mensaje si está fuera de rango
            except ValueError:
                print("⚠️ Ingresá un número válido.")             # Mensaje si no es un número

    alumnos[nombre] = notas                   # Asigno la lista de notas al nombre del alumno

print("\n📊 Promedios de los alumnos:")
for nombre, notas in alumnos.items():         # Recorro el diccionario
    promedio = sum(notas) / len(notas)        # Calculo el promedio
    estado = "✅ Aprobado" if promedio >= 7 else "❌ Desaprobado"  # Verifico si aprobó
    print(f"{nombre}: Promedio = {promedio:.2f} → {estado}")      # Muestro el resultado

"""7) Dado dos sets de números, representando dos listas de estudiantes que aprobaron Parcial 1
y Parcial 2:

• Mostrá los que aprobaron ambos parciales.

• Mostrá los que aprobaron solo uno de los dos.

• Mostrá la lista total de estudiantes que aprobaron al menos un parcial (sin repetir).

"""

# Diccionarios con alumnos y sus notas
parcial1 = {'Facu': 8, 'Luz': 6, 'Nico': 7, 'Meli': 9, 'Goku' : 10}             # Guardo las notas del primer parcial
parcial2 = {'Facu': 7, 'Luz': 9, 'Juli': 6, 'Meli': 8, 'Goku' : 10}             # Guardo las notas del segundo parcial

# Filtrar aprobados (nota >= 7)
aprobados1 = {alumno for alumno, nota in parcial1.items() if nota >= 7}        # Creo un set con los que aprobaron el primer parcial
aprobados2 = {alumno for alumno, nota in parcial2.items() if nota >= 7}        # Creo otro set con los que aprobaron el segundo

# Intersección: aprobó ambos
ambos = aprobados1 & aprobados2                                                 # Uso la intersección para ver quién aprobó los dos
print("✅ Aprobó ambos:", ambos)

# Diferencia simétrica: aprobó solo uno
solo_uno = aprobados1 ^ aprobados2                                              # Uso la diferencia simétrica para ver quién aprobó solo uno
print("⚠️ Aprobó solo uno:", solo_uno)

# Unión: aprobó al menos uno
al_menos_uno = aprobados1 | aprobados2                                          # Uso la unión para ver quién aprobó al menos uno
print("📋 Aprobó al menos un parcial:", al_menos_uno)

"""8) Armá un diccionario donde las claves sean nombres de productos y los valores su stock.

Permití al usuario:

• Consultar el stock de un producto ingresado.

• Agregar unidades al stock si el producto ya existe.

• Agregar un nuevo producto si no existe.
"""

stock_productos = {}                                                           # Creo un diccionario vacío para almacenar productos y su stock

while True:                                                                    # Inicio un bucle infinito para mostrar el menú hasta que el usuario decida salir
    print("\n📦 Menú de opciones:")                                            # Muestro el menú de opciones
    print("1. Consultar stock de un producto")
    print("2. Agregar unidades al stock")
    print("3. Agregar nuevo producto")
    print("4. Salir")

    opcion = input("Elegí una opción (1-4): ")                                 # Pido al usuario que elija una opción

    if opcion == "1":                                                          # Opción 1: consultar stock
        if not stock_productos:                                                # Si el diccionario está vacío
            print("📭 No hay productos cargados en el inventario.")
        else:
            print("📋 Productos disponibles:", ", ".join(stock_productos.keys()))  # Muestro los productos disponibles
            producto = input("🔍 Ingresá el nombre del producto a consultar: ").capitalize()
            if producto in stock_productos:                                    # Si el producto existe
                print(f"✅ El stock de {producto} es: {stock_productos[producto]} unidades")
            else:
                print(f"❌ El producto '{producto}' no existe en el inventario")

    elif opcion == "2":                                                        # Opción 2: agregar unidades al stock
        producto = input("➕ Ingresá el nombre del producto al que querés agregar stock: ").capitalize()
        if producto in stock_productos:                                        # Si el producto existe
            try:
                cantidad = int(input("¿Cuántas unidades querés agregar?: "))   # Pido la cantidad
                stock_productos[producto] += cantidad                          # Sumo al stock actual
                print(f"✅ Se agregaron {cantidad} unidades a {producto}. Nuevo stock: {stock_productos[producto]}")
            except ValueError:
                print("⚠️ Ingresá una cantidad válida (número entero)")
        else:
            print(f"❌ El producto '{producto}' no existe. Usá la opción 3 para agregarlo.")

    elif opcion == "3":                                                        # Opción 3: agregar nuevo producto
        producto = input("🆕 Ingresá el nombre del nuevo producto: ").capitalize()
        if producto in stock_productos:                                        # Si ya existe
            print(f"⚠️ El producto '{producto}' ya existe. Usá la opción 2 para agregar stock.")
        else:
            try:
                cantidad = int(input("¿Cuántas unidades tiene en stock?: "))   # Pido el stock inicial
                stock_productos[producto] = cantidad                           # Lo agrego al diccionario
                print(f"✅ Producto '{producto}' agregado con {cantidad} unidades.")
            except ValueError:
                print("⚠️ Ingresá una cantidad válida (número entero)")

    elif opcion == "4":                                                        # Opción 4: salir del programa
        print("👋 Cerrando el programa. ¡Hasta la próxima!")
        break

    else:                                                                      # Si la opción no es válida
        print("⚠️ Opción inválida. Elegí entre 1 y 4.")

"""9) Creá una agenda donde las claves sean tuplas de (día, hora) y los valores sean eventos.

Permití consultar qué actividad hay en cierto día y hora.
"""

import unicodedata                                                           # Importo la librería para poder quitar acentos

def normalizar(texto):                                                      # Defino una función para normalizar el texto
    texto = unicodedata.normalize('NFKD', texto)                            # Aplico la normalización Unicode
    texto = texto.encode('ASCII', 'ignore').decode('utf-8')                # Elimino los caracteres no ASCII (como acentos)
    return texto.lower()                                                   # Devuelvo el texto en minúsculas

agenda = {                                                                  # Creo un diccionario con eventos, usando tuplas (día, hora) como claves
    ("lunes", "10:00"): "Reunión de equipo",
    ("lunes", "15:30"): "Llamada con cliente",
    ("martes", "14:30"): "Clase de programación",
    ("miercoles", "09:00"): "Consulta médica",
    ("viernes", "18:00"): "Gimnasio",
    ("domingo", "9:30"): "Clase de golf"
}

dias_validos = ["lunes", "martes", "miercoles", "jueves",                  # Lista de días válidos sin acento
                "viernes", "sabado", "domingo"]

while True:                                                                 # Bucle para validar el día ingresado
    dia_input = input("📅 Ingresá el día que querés consultar (ej. Lunes): ")
    dia_normalizado = normalizar(dia_input)                                 # Normalizo el texto ingresado
    if dia_normalizado in dias_validos:                                     # Verifico si es un día válido
        break
    print("⚠️ Día inválido. Ingresá un día de la semana correctamente.")

eventos_del_dia = [(hora, evento)                                          # Recorro la agenda y filtro los eventos del día ingresado
                   for (d, hora), evento in agenda.items() if d == dia_normalizado]

if eventos_del_dia:                                                        # Si hay eventos para ese día
    print(f"\n📆 Actividades para el día {dia_input.capitalize()}:")
    for hora, evento in sorted(eventos_del_dia):                           # Ordeno por hora y muestro cada evento
        print(f"🕒 {hora} → {evento}")
else:                                                                       # Si no hay eventos
    print(f"📭 No hay actividades programadas para el día {dia_input.capitalize()}.")

"""10) Dado un diccionario que mapea nombres de países con sus capitales, construí un nuevo diccionario donde:

• Las capitales sean las claves.

• Los países sean los valores.
"""

# Diccionario original: país → capital
paises = {
    "Argentina": "Buenos Aires",
    "Brasil": "Brasilia",
    "Chile": "Santiago",
    "Uruguay": "Montevideo",
    "Paraguay": "Asunción"
}                                                                                 # Creo un diccionario con países como claves y capitales como valores

print("🌎 Diccionario original (país → capital):")
for pais, capital in paises.items():                                             # Recorro el diccionario y muestro cada país con su capital
    print(f"{pais} → {capital}")

capitales = {}                                                                   # Creo un nuevo diccionario vacío para invertir los datos
for pais, capital in paises.items():                                             # Recorro el diccionario original
    capitales[capital] = pais                                                    # Asigno la capital como clave y el país como valor

print("\n🏙️ Diccionario invertido (capital → país):")
for capital, pais in capitales.items():                                          # Muestro el nuevo diccionario invertido
    print(f"{capital} → {pais}")