# -*- coding: utf-8 -*-
"""Manejo de Archivos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzhKx287GeFglO5-lIO120JwYVz7rtuX

# Trabajo Práctico – Manejo de Archivos | Juan Facundo Escalante DNI:24927651
Objetivo:

Comprender y aplicar el uso de archivos de texto en Python, desarrollando un
pequeño programa que lea, procese y almacene información sobre productos de
manera persistente. Se busca que el estudiante manipule datos a través de
estructuras como listas y diccionarios, integrando lectura, escritura y buenas prácticas
con archivos.

1. Crear archivo inicial con productos: Crear un archivo de texto llamado
productos.txt con tres productos. Cada línea debe tener:  nombre,precio,cantidad
"""

productos = [                                                                               # Creo una lista llamada 'productos' que contiene tres líneas de texto
    "yogurt griego,1500,20\n",
    "arandanos,1800,10\n",
    "atun,2500,12\n"
]

with open("productos.txt", "w") as archivo:                                                 # Abro (o creo) el archivo 'productos.txt' en modo escritura
    archivo.writelines(productos)                                                           # Escribo todas las líneas de la lista en el archivo de una sola vez

"""2. Leer y mostrar productos: Crear un programa que abra productos.txt, lea cada
línea, la procese con .strip() y .split(","), y muestre los productos en el siguiente
formato:

Producto: Lapicera | Precio: $120.5 | Cantidad: 30
"""

with open("productos.txt", "r") as archivo:                                                        # Abro el archivo 'productos.txt' en modo lectura
    for linea in archivo:                                                                          # Recorro cada línea del archivo una por una
        nombre, precio, cantidad = linea.strip().split(",")                                        # Elimino espacios y salto de línea, luego separo los datos por comas
        print(f"Producto: {nombre} | Precio: ${precio} | Cantidad: {cantidad}")                    # Muestro los datos del producto en formato legible

"""3. Agregar productos desde teclado: Modificar el programa para que luego de mostrar
los productos, le pida al usuario que ingrese un nuevo producto (nombre, precio,
cantidad) y lo agregue al archivo sin borrar el contenido existente.
"""

# Paso 1: Leer productos existentes en diccionario
productos = {}                                                                           # Inicializo un diccionario vacío donde voy a guardar los productos

with open("productos.txt", "r") as archivo:                                               # Abro el archivo 'productos.txt' en modo lectura
    for linea in archivo:                                                                 # Recorro cada línea del archivo una por una
        nombre, precio, cantidad = linea.strip().split(",")                               # Elimino espacios y separo los datos por comas
        nombre = nombre.lower()                                                           # Paso el nombre a minúsculas para evitar duplicados por mayúsculas
        productos[nombre] = {                                                             # Guardo los datos en el diccionario con el nombre como clave
            "precio": float(precio),                                                      # Convierto el precio a número decimal
            "cantidad": int(cantidad)                                                     # Convierto la cantidad a número entero
        }

# Mostrar productos actuales
print(" Productos actuales:")                                                           # Imprimo un título para mostrar los productos
for nombre, datos in productos.items():                                                    # Recorro el diccionario de productos
    print(f"Producto: {nombre} | Precio: ${datos['precio']} | Cantidad: {datos['cantidad']}")  # Muestro cada producto en formato legible

# Paso 2: Ingresar productos en bucle
while True:                                                                                # Inicio un bucle infinito para ingresar productos
    print("\n Ingresar nuevo producto:")                                                 # Imprimo un mensaje para indicar el ingreso de datos
    nombre = input("Nombre (o 'salir' para terminar): ").strip().lower()                   # Pido el nombre del producto y lo normalizo
    if nombre == "salir":                                                                  # Si el usuario escribe 'salir', corto el bucle
        break

    # Validación de precio
    while True:                                                                             # Inicio un bucle para validar el precio
        try:                                                                                # Intento convertir el precio a float
            precio = float(input("Precio: "))                                               # Pido el precio del producto
            if precio <= 0:                                                                 # Verifico que el precio sea mayor a cero
                print(" El precio debe ser mayor a 0.")                                   # Muestro advertencia si no lo es
            else:
                break                                                                         # Si el precio es válido, salgo del bucle
        except ValueError:                                                                    # Si el usuario ingresa algo que no es número
            print("Ingresá un número válido para el precio.")                             # Muestro mensaje de error

    # Validación de cantidad
    while True:                                                                                # Inicio un bucle para validar la cantidad
        try:                                                                                  # Intento convertir la cantidad a entero
            cantidad = int(input("Cantidad: "))                                               # Pido la cantidad del producto
            if cantidad < 0:                                                                      # Verifico que no sea negativa
                print(" La cantidad no puede ser negativa.")                                # Muestro advertencia si lo es
            else:
                break                                                                           # Si la cantidad es válida, salgo del bucle
        except ValueError:                                                                     # Si el usuario ingresa algo que no es número
            print(" Ingresá un número entero válido para la cantidad.")                      # Muestro mensaje de error

    # Sumar si es duplicado o agregar nuevo
    if cantidad > 0:                                                                            # Verifico que la cantidad sea mayor a cero
        if nombre in productos:                                                                 # Si el producto ya existe en el diccionario
            productos[nombre]["cantidad"] += cantidad                                            # Sumo la nueva cantidad a la existente
            productos[nombre]["precio"] = precio                                                 # Actualizo el precio (por si cambió)
        else:                                                                                       # Si el producto no existe
            productos[nombre] = {"precio": precio, "cantidad": cantidad}                           # Lo agrego como nuevo
    else:                                                                                         # Si la cantidad es cero
        print(" No se agregó el producto porque la cantidad es 0.")                            # Muestro mensaje de advertencia

# Paso 3: Guardar todos los productos actualizados
with open("productos.txt", "w") as archivo:                                                      # Abro el archivo en modo escritura (sobrescribe contenido)
    for nombre, datos in productos.items():                                                      # Recorro el diccionario de productos
        archivo.write(f"{nombre},{datos['precio']},{datos['cantidad']}\n")                       # Escribo cada producto en formato CSV

# Paso 4: Mostrar productos actualizados
print("\n✅ Productos actualizados:")                                                            # Imprimo un título para mostrar los productos finales
for nombre, datos in productos.items():                                                         # Recorro el diccionario de productos
    print(f"Producto: {nombre} | Precio: ${datos['precio']} | Cantidad: {datos['cantidad']}")  # Muestro cada producto actualizado

"""4. Cargar productos en una lista de diccionarios: Al leer el archivo, cargar los datos en
una lista llamada productos, donde cada elemento sea un diccionario con claves:
nombre, precio, cantidad.
"""

productos = []                                                                   # Inicializo una lista vacía

with open("productos.txt", "r") as archivo:                                        # Abro el archivo 'productos.txt' en modo lectura
    for linea in archivo:                                                          # Recorro cada línea del archivo una por una
        nombre, precio, cantidad = linea.strip().split(",")                        # Elimino espacios y salto de línea, luego separo los datos por comas
        producto = {"nombre": nombre, "precio": precio, "cantidad": cantidad}      # Creo un diccionario con los datos del producto
        productos.append(producto)                                                 # Agrego el diccionario a la lista 'productos'

for p in productos:                                                                  # Recorro la lista de productos
  print(p)                                                                           # Muestro cada producto como diccionario en la consola

"""5. Buscar producto por nombre: Pedir al usuario que ingrese el nombre de un
producto. Recorrer la lista de productos y, si lo encuentra, mostrar todos sus datos. Si
no existe, mostrar un mensaje de error.
"""

productos = []                                                                      # Inicializo una lista vacía

with open("productos.txt", "r") as archivo:                                         # Abro el archivo 'productos.txt' en modo lectura
    for linea in archivo:                                                           # Recorro cada línea del archivo una por una
        nombre, precio, cantidad = linea.strip().split(",")                         # Elimino espacios y salto de línea, luego separo los datos por comas
        producto = {"nombre": nombre, "precio": precio, "cantidad": cantidad}       # Creo un diccionario con los datos del producto
        productos.append(producto)                                                  # Agrego el diccionario a la lista 'productos'

buscar = input("Ingrese el nombre del producto a buscar: ")                         # Pido al usuario el nombre del producto que quiere buscar
encontrado = False                                                                  # Inicializo una bandera para saber si lo encuentro

for p in productos:                                                                 # Recorro la lista de productos
    if p["nombre"] == buscar:                                                       # Si el nombre del producto coincide con el buscado
        print(f"Producto: {p['nombre']} | Precio: ${p['precio']} | Cantidad: {p['cantidad']}")  # Muestro los datos del producto
        encontrado = True                                                                       # Marco que lo encontré
        break                                                                                   # Salgo del bucle porque ya lo encontré

if not encontrado:                                                                              # Si no se encontró ningún producto con ese nombre
    print("Producto no encontrado.")                                                            # Muestro un mensaje de error

"""6. Guardar los productos actualizados: Después de haber leído, buscado o agregado
productos, sobrescribir el archivo productos.txt escribiendo nuevamente todos los
productos actualizados desde la lista.
"""

productos = {                                                                          # Inicializo un diccionario con productos base
    "lapicera": {"precio": 120.5, "cantidad": 30},
    "cuaderno": {"precio": 350.0, "cantidad": 15},
    "goma": {"precio": 50.0, "cantidad": 40}
}

# Leer archivo y agregar productos nuevos
with open("productos.txt", "r") as archivo:                                                 # Abro el archivo en modo lectura
    for linea in archivo:                                                                    # Recorro cada línea del archivo
        nombre, precio, cantidad = linea.strip().split(",")                                 # Elimino espacios y separo los datos por comas
        precio = float(precio)                                                               #  Convierto el precio a número decimal
        cantidad = int(cantidad)                                                             # Convierto la cantidad a número entero

        if nombre in productos:                                                              # Si el producto ya existe en el diccionario
            productos[nombre]["cantidad"] += cantidad                                        # Sumo la cantidad nueva a la existente
            productos[nombre]["precio"] = precio                                             # Actualizo el precio (opcional)
        else:  # Si el producto no existe
            productos[nombre] = {"precio": precio, "cantidad": cantidad}                     # Lo agrego como nuevo

# Guardar todos los productos actualizados
with open("productos.txt", "w") as archivo:                                                   # Abro el archivo en modo escritura (borra contenido anterior)
    for nombre, datos in productos.items():                                                     # Recorro el diccionario de productos
        archivo.write(f"{nombre},{datos['precio']},{datos['cantidad']}\n")                    # Escribo cada producto en formato CSV

print(" Archivo productos.txt actualizado sumando duplicados.")                            # Confirmo que el archivo fue sobrescrito correctamente
print(" Productos actualizados:\n")                                                        # Imprimo un título para mostrar los productos

for nombre, datos in productos.items():                                                          # Recorro el diccionario de productos
    print(f"Producto: {nombre} | Precio: ${datos['precio']} | Cantidad: {datos['cantidad']}")  # Muestro cada producto en formato legible