# -*- coding: utf-8 -*-
"""Práctico 2: Funciones en Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14yh7o3M1cFRQrXDk9EFYds_Wq-DChfQE

# **Práctico 2: Funciones en Python**

**Juan Facundo Escalante DNI:24927651**

1. Crear una función llamada imprimir_hola_mundo que imprima por
 pantalla el mensaje: “Hola Mundo!”. Llamar a esta función desde el
 programa principal.
"""

def imprimir_hola_mundo():             # defino la función que imprime el saludo
    print("Hola Mundo!")               # muestro el mensaje por pantalla

imprimir_hola_mundo()                  # llamo a la función para ejecutar el saludo

""" 2. Crear una función llamada saludar_usuario(nombre) que reciba
 como parámetro un nombre y devuelva un saludo personalizado.
 Por ejemplo, si se llama con saludar_usuario("Marcos"), deberá de
volver: “Hola Marcos!”. Llamar a esta función desde el programa
 principal solicitando el nombre al usuario.
"""

def saludar_usuario(nombre):                      # defino la función que saluda al usuario
    print(f"Hola {nombre}!")                      # muestro el saludo con el nombre ingresado

nombre = input("Ingrese su nombre: ")             # solicito el nombre al usuario

saludar_usuario(nombre)                           # llamo a la función con el nombre ingresado

""" 3. Crear una función llamada informacion_personal(nombre, apellido,
 edad, residencia) que reciba cuatro parámetros e imprima: “Soy
 [nombre] [apellido], tengo [edad] años y vivo en [residencia]”. Pe
dir los datos al usuario y llamar a esta función con los valores in
gresados.
"""

def informacion_personal(nombre, apellido, edad, residencia):     # defino la función que muestra la información personal
    informacion = f"Soy {nombre} {apellido}, tengo {edad} años y vivo en {residencia}."  # armo el mensaje con los datos
    print(informacion)                                             # muestro el mensaje por pantalla

nombre = input("Ingrese su nombre: ")                              # solicito el nombre al usuario
apellido = input("Ingrese su apellido: ")                          # solicito el apellido al usuario

# valido que la edad sea un número y no esté vacía
while True:
    edad = input("Ingrese su edad: ")                              # solicito la edad al usuario
    if edad.isdigit():                                             # verifico que la edad sea numérica
        break                                                      # si es válida, salgo del bucle
    else:
        print("Por favor ingrese una edad válida.")                # muestro mensaje si no es válida

residencia = input("Ingrese su residencia: ")                      # solicito la residencia al usuario

informacion_personal(nombre, apellido, edad, residencia)           # llamo a la función con los datos ingresados

""" 4. Crear dos funciones: calcular_area_circulo(radio) que reciba el ra
dio como parámetro y devuelva el área del círculo. calcular_peri
metro_circulo(radio) que reciba el radio como parámetro y devuel
va el perímetro del círculo. Solicitar el radio al usuario y llamar am
bas funciones para mostrar los resultados.
"""

def calcular_area_circulo(radio):                      # defino la función para calcular el área
    area = 3.14159 * radio**2                          # calculo el área usando la fórmula π * r²
    return area                                        # retorno el valor del área

def calcular_perimetro_circulo(radio):                 # defino la función para calcular el perímetro
    perimetro = 2 * 3.14159 * radio                    # calculo el perímetro usando la fórmula 2 * π * r
    return perimetro                                   # retorno el valor del perímetro

radio_valido = False                                   # inicializo la variable para validar el radio

while not radio_valido:                                # valido que el radio ingresado sea correcto
    radio = float(input("Ingrese el radio del círculo: "))  # solicito al usuario el valor del radio

    if radio > 0:                                      # valido que el radio sea mayor a cero
        radio_valido = True                            # confirmo que el radio es válido
    else:
        print("El radio debe ser mayor a cero.")       # informo que el radio no es válido

area = calcular_area_circulo(radio)                    # llamo a la función para calcular el área
perimetro = calcular_perimetro_circulo(radio)          # llamo a la función para calcular el perímetro

print(f"El área del círculo es: {area:.2f}")           # muestro el área con 2 decimales
print(f"El perímetro del círculo es: {perimetro:.2f}") # muestro el perímetro con 2 decimales

""" 5. Crear una función llamada segundos_a_horas(segundos) que reciba
 una cantidad de segundos como parámetro y devuelva la cantidad
 de horas correspondientes. Solicitar al usuario los segundos y mostrar el resultado usando esta función.
"""

def segundos_a_horas(segundos):                         # defino la función que convierte segundos a horas
    conversor = segundos / 3600                         # convierto los segundos a horas (1 hora = 3600 segundos)
    return conversor                                    # retorno el resultado de la conversión

segundos = float(input("Ingrese la cantidad de segundos: "))  # pido al usuario la cantidad de segundos
horas = segundos_a_horas(segundos)                     # llamo a la función y guardo el resultado en 'horas'
print(f"{segundos:.0f} segundos equivalen a {horas:.2f} horas.")  # muestro el resultado con 2 decimales

""" 6. Crear una función llamada tabla_multiplicar(numero) que reciba un
 número como parámetro y imprima la tabla de multiplicar de ese
 número del 1 al 10. Pedir al usuario el número y llamar a la fun
ción.
"""

def tabla_multiplicar(numero):                             # defino la función que muestra la tabla
    for i in range(1, 11):                                 # recorro los números del 1 al 10
        print(f"{int(numero)} x {i} = {int(numero) * i}")  # muestro la multiplicación sin decimales

numero_valido = False                                      # inicializo la variable para validar el número

while not numero_valido:                                   # valido que el número ingresado sea correcto
    entrada = input("Ingrese un número del 1 al 10: ")     # pido el número al usuario

    if entrada.replace('.', '', 1).isdigit():              # verifico si la entrada es numérica
        numero = float(entrada)                            # convierto la entrada a número decimal

        if 1 <= numero <= 10:                              # valido que esté entre 1 y 10
            numero_valido = True                           # confirmo que el número es válido
        else:
            print("El número debe estar entre 1 y 10.")    # informo que está fuera de rango
    else:
        print("Entrada inválida. Por favor ingrese un número.")  # informo que no es un número

tabla_multiplicar(numero)                                  # llamo a la función con el número validado

"""7. Crear una función llamada operaciones_basicas(a, b) que reciba
 dos números como parámetros y devuelva una tupla con el resulta
do de sumarlos, restarlos, multiplicarlos y dividirlos. Mostrar los re
sultados de forma clara.
"""

def operaciones_basicas(a, b):                          # defino la función que realiza operaciones básicas
    suma = a + b                                        # calculo la suma
    resta = a - b                                       # calculo la resta
    multiplicacion = a * b                              # calculo la multiplicación

    if b != 0:                                          # valido que el divisor no sea cero
        division = a / b                                # calculo la división si es válida
    else:
        division = "No se puede dividir por cero"       # asigno mensaje si no se puede dividir

    return suma, resta, multiplicacion, division        # retorno los cuatro resultados

# valido que el primer número sea correcto
while True:
    entrada_a = input("Ingrese el primer número: ")     # solicito el primer número al usuario
    if entrada_a.replace('.', '', 1).isdigit():         # verifico que sea numérico (permite decimales)
        a = float(entrada_a)                            # convierto a número decimal
        break                                           # salgo del bucle si es válido
    else:
        print("Entrada inválida. Ingrese solo números.")# muestro mensaje si no es válido

# valido que el segundo número sea correcto
while True:
    entrada_b = input("Ingrese el segundo número: ")    # solicito el segundo número al usuario
    if entrada_b.replace('.', '', 1).isdigit():         # verifico que sea numérico (permite decimales)
        b = float(entrada_b)                            # convierto a número decimal
        break                                           # salgo del bucle si es válido
    else:
        print("Entrada inválida. Ingrese solo números.")# muestro mensaje si no es válido

suma, resta, multiplicacion, division = operaciones_basicas(a, b)  # llamo a la función y guardo los resultados

print(f"Suma: {suma:.2f}")                              # muestro la suma con 2 decimales
print(f"Resta: {resta:.2f}")                            # muestro la resta con 2 decimales
print(f"Multiplicación: {multiplicacion:.2f}")          # muestro la multiplicación con 2 decimales
print(f"División: {division if isinstance(division, str) else f'{division:.2f}'}")  # muestro la división o el mensaje

""" 8. Crear una función llamada calcular_imc(peso, altura) que reciba el
 peso en kilogramos y la altura en metros, y devuelva el índice de
 masa corporal (IMC). Solicitar al usuario los datos y llamar a la fun
ción para mostrar el resultado con dos decimales.
"""

def calcular_imc(peso, altura):                             # defino la función que calcula el IMC
    imc = peso / altura**2                                  # calculo el IMC usando la fórmula peso / altura²
    return imc                                              # retorno el resultado del IMC

# valido que el peso sea correcto
while True:
    entrada_peso = input("Ingrese su peso en kilogramos: ") # solicito el peso al usuario
    if entrada_peso.replace('.', '', 1).isdigit():          # verifico que sea numérico (permite decimales)
        peso = float(entrada_peso)                          # convierto a número decimal
        break                                               # salgo del bucle si es válido
    else:
        print("Entrada inválida. Ingrese solo números.")    # muestro mensaje si no es válido

# valido que la altura sea correcta, mayor a cero y menor al tope
while True:
    entrada_altura = input("Ingrese su altura en metros: ") # solicito la altura al usuario
    if entrada_altura.replace('.', '', 1).isdigit():        # verifico que sea numérico (permite decimales)
        altura = float(entrada_altura)                      # convierto a número decimal
        if 0 < altura <= 2.5:                               # valido que esté dentro del rango permitido
            break                                           # salgo del bucle si es válida
        else:
            print("La altura debe estar entre 0 y 2.5 metros.")  # muestro mensaje si está fuera de rango
    else:
        print("Entrada inválida. Ingrese solo números.")    # muestro mensaje si no es válida

imc = calcular_imc(peso, altura)                            # llamo a la función para calcular el IMC
print(f"Su índice de masa corporal (IMC) es: {imc:.2f}")    # muestro el resultado con 2 decimales

""" 9. Crear una función llamada celsius_a_fahrenheit(celsius) que reciba
 una temperatura en grados Celsius y devuelva su equivalente en
 Fahrenheit. Pedir al usuario la temperatura en Celsius y mostrar el
 resultado usando la función.
"""

def celsius_a_fahrenheit(celsius):                             # defino la función que convierte Celsius a Fahrenheit
    fahrenheit = (celsius * 9/5) + 32                           # convierto usando la fórmula (C × 9/5) + 32
    return fahrenheit                                          # retorno el resultado

# valido que la entrada sea numérica
while True:
    entrada = input("Ingrese la temperatura en grados Celsius: ")  # solicito la temperatura al usuario
    if entrada.replace('.', '', 1).replace('-', '', 1).isdigit():  # valido que sea número (permite negativos y decimales)
        temperatura_celsius = float(entrada)                       # convierto a número decimal
        break                                                      # salgo del bucle si es válida
    else:
        print("Entrada inválida. Ingrese solo números.")           # muestro mensaje si no es válida

temperatura_fahrenheit = celsius_a_fahrenheit(temperatura_celsius)  # llamo a la función para convertir

print(f"{temperatura_celsius:.2f} °C equivalen a {temperatura_fahrenheit:.2f} °F.")  # muestro el resultado con 2 decimales

""" 10.Crear una función llamada calcular_promedio(a, b, c) que reciba
 tres números como parámetros y devuelva el promedio de ellos.
 Solicitar los números al usuario y mostrar el resultado usando esta
 función.
"""

def calcular_promedio(a, b, c):                  # defino la función que calcula el promedio
    promedio = (a + b + c) / 3                   # calculo el promedio correctamente con paréntesis
    return promedio                              # retorno el resultado

# valido que las entradas sean numéricas
while True:
    entrada1 = input("Ingrese el primer número: ")  # solicito el primer número
    entrada2 = input("Ingrese el segundo número: ") # solicito el segundo número
    entrada3 = input("Ingrese el tercer número: ")  # solicito el tercer número

    if (entrada1.replace('.', '', 1).isdigit() and
        entrada2.replace('.', '', 1).isdigit() and
        entrada3.replace('.', '', 1).isdigit()):     # valido que los tres sean números
        a = float(entrada1)                          # convierto a número decimal
        b = float(entrada2)
        c = float(entrada3)
        break                                        # salgo del bucle si son válidos
    else:
        print("Entrada inválida. Ingrese solo números.")  # muestro mensaje si hay error

promedio = calcular_promedio(a, b, c)              # llamo a la función para calcular el promedio
print(f"El promedio es: {promedio:.2f}")           # muestro el resultado con 2 decimales