# -*- coding: utf-8 -*-
"""Práctico4:Estructuras repetitivas	.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xl60qiglzpJXPzP5ZUj195C7xoYjnRC8

# Práctico	4:	Estructuras	repetitivas	🐍

🧑 Juan Facundo Escalante DNI: 24927651

1) Crea un programa que imprima en pantalla todos los números enteros desde 0 hasta 100
(incluyendo ambos extremos), en orden creciente, mostrando un número por línea.
"""

numentreos = 0

while numentreos <= 100:
    print(numentreos)
    numentreos += 1

"""2) Desarrolla un programa que solicite al usuario un número entero y determine la cantidad de
dígitos que contiene.
"""

nument = int(input("Ingrese un número entero: ")) #solicito valor
digito = 0                  #inicializo

while nument > 0:           #mientras sea mayor a cero
    nument //= 10           #divide x 10 y descarta decimales
    digito += 1             #suma 1 por cada digito eliminado
print("La cantidad de dígitos es:", digito)

"""3) Escribe un programa que sume todos los números enteros comprendidos entre dos valores
dados por el usuario, excluyendo esos dos valores.
"""

num1 = int(input("Ingrese el primer número: ")) #defino variables
num2 = int(input("Ingrese el segundo número: ")) #defino variables

if num1 > num2:                             #intercambia valores si el primero es mayor
    num1, num2 = num2, num1

suma = 0
for i in range(num1 + 1, num2):         #recorre los nros entre num1 y num2, excluyendo a ambos
    suma += i                       #suma los valores de i en el rango
    print(i)
print("La suma de los números comprendidos entre", num1, "y", num2, "es:", suma)

"""4) Elabora un programa que permita al usuario ingresar números enteros y los sume en
secuencia. El programa debe detenerse y mostrar el total acumulado cuando el usuario ingrese
un 0.
"""

num = int(input("Ingrese un número entero: ")) #solicito valor

suma = 0                                  #inicializo
while num != 0:                           #mientras sea distinto a cero
    suma += num                           #va sumando num a la variable suma
    num = int(input("Ingrese otro número entero (ingrese 0 para detenerse): ")) #pide otro nro si no es cero
    if num == 0:                              #aca se detiene
      print("El total acumulado es:", suma)  #muestra total acumuldo

"""5) Crea un juego en el que el usuario deba adivinar un número aleatorio entre 0 y 9. Al final, el
programa debe mostrar cuántos intentos fueron necesarios para acertar el número.
"""

import random              #importo libreria random
num = random.randint(0, 9) #numero aleatorio entre 0 y 9
numAlea = 0                #inicializo variables
intentos = 0

while numAlea != num:       #mientras nro alea sea distinto al nro random
    numAlea = int(input("Ingrese un número entre 0 y 9: ")) #pide otro nro
    intentos += 1                                           #suma cant de intentos
    if numAlea == num:                                      #si el nro coincide, muestra la felicitacion!!
        print("Felicitaciones! Adivinaste el número en", intentos, "intentos.")

"""6) Desarrolla un programa que imprima en pantalla todos los números pares comprendidos
entre 0 y 100, en orden decreciente.
"""

num = 100           #inicializo variable

while num >= 0:     #mientras nro sea mayor o igual a ceo
  if num % 2 == 0:  #si el resto es cero es par
    print(num)      #imprime nro
  num -= 1          #resta uno a num, decremento

"""7) Crea un programa que calcule la suma de todos los números comprendidos entre 0 y un
número entero positivo indicado por el usuario.
"""

num = int(input("Ingrese un número entero positivo: ")) #solicito valor
suma = 0

for i in range(0, num + 1):                             #recorre desde cero al nro ingresado incluido
  suma += i                                         #acumula la suma

print("La suma de todos los números comprendidos entre 0 y", num, "es:", suma)

"""8) Escribe un programa que permita al usuario ingresar 100 números enteros. Luego, el
programa debe indicar cuántos de estos números son pares, cuántos son impares, cuántos son
negativos y cuántos son positivos. (Nota: para probar el programa puedes usar una cantidad
menor, pero debe estar preparado para procesar 100 números con un solo cambio).
"""

import random                                   #importo libreria random
nupar = 0                                     #defino varialbles
nuimp = 0
nunega = 0
nupos = 0                                      #defino varialbles

numeros = []                                    #lista guardo nros ingresados o laeatorios

for i in range(100):                               #recorre 100 veces
  num = random.randint(-100, 100)                  #opcion random
  #num = int(input("Ingrese un número entero: "))  #solicito valor
  numeros.append(num)                              #guardo nros en la listA

  if num % 2 == 0:                                #si el resto es cero es par
    nupar += 1
  else:
    nuimp += 1

  if num > 0:                                    #si es negativo
    nupos += 1
  elif num < 0:
    nunega += 1

print("La cantidad de números pares es:", nupar)
print("La cantidad de números impares es:", nuimp)
print("La cantidad de números negativos es:", nunega)
print("La cantidad de números positivos es:", nupos)

print("Números generados:")
print(numeros)

"""9) Elabora un programa que permita al usuario ingresar 100 números enteros y luego calcule la
media de esos valores. (Nota: puedes probar el programa con una cantidad menor, pero debe
poder procesar 100 números cambiando solo un valor).
"""

import random                              #importo libreria random
num = 0                                  #defino varialbles
media = 0
numeros = []                             #lista guardo nros ingresados o laeatorios

for i in range(100):                       #recorre 100 veces la lista
  num = random.randint(0, 100)             #opcion random
  #num = int(input("Ingrese un número entero: ")) #opcion manual
  media += num / 100                        #suma y / 100
  numeros.append(num)                       #guarda nros en la lista

print("La media de los números ingresados es:", media)
print("Números generados:")
print(numeros)                               #imprime lista

"""10) Escribe un programa que invierta el orden de los dígitos de un número ingresado por el
usuario. Ejemplo: si el usuario ingresa 547, el programa debe mostrar 745.
"""

num = int(input("Ingrese un número entero: ")) #solicito valor
invertido = 0                                  #inicializo variable

while num > 0:                                  #mientrasnro sea mayor a cero
    digito = num % 10                           #extrae el ultimo digito
    invertido = invertido * 10 + digito         #agreag el digito al final del nro invertido
    num //= 10                                  #elimina el ultimo digito del nro original
print("El número invertido es:", invertido)